# Generated by Django 4.1.3 on 2023-07-05 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_item_items_quotation_remove_user_invoice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='size',
            field=models.CharField(blank=True, choices=[('AS PER DESIGN', 'AS PER DESIGN'), ('LENGTH HEIGHT', 'LENGTH HEIGHT')], max_length=100, null=True),
        ),
    ]
