# Generated by Django 4.1.3 on 2023-07-07 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_items_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='unit',
            field=models.CharField(blank=True, choices=[('METER', 'METER'), ('CENTI METER', 'CENTI METER'), ('INCH', 'INCH')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='client_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='user_client',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='size',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
