# Generated by Django 4.1.3 on 2023-05-11 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_user_remove_shipping_invoice_invoice_bill_of_lading_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Desc',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='desc_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='quantity',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='rate',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='sac',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
