# Generated by Django 4.1.3 on 2023-06-17 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_client_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='billing_state',
        ),
        migrations.RemoveField(
            model_name='client',
            name='shipping_state',
        ),
    ]
