# Generated by Django 4.1.3 on 2023-06-17 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_client_billing_state_client_shipping_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='billing_state',
            new_name='billing_state1',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='shipping_state',
            new_name='shipping_state1',
        ),
    ]
