# Generated by Django 4.1.3 on 2023-07-08 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_client_user_client'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='user_client',
            new_name='user_client_id',
        ),
        migrations.AddField(
            model_name='client',
            name='user_client_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
