# Generated by Django 4.1.3 on 2023-06-17 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_billing_state_client_billing_state1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='billing_state1',
            new_name='billing_state',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='shipping_state1',
            new_name='shipping_state',
        ),
    ]
