# Generated by Django 4.1.3 on 2023-07-10 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_user_client_client_user_client_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='item_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
