# Generated by Django 4.1.3 on 2023-06-28 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_billing_state1_client_billing_state_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProformInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('client_id', models.CharField(blank=True, max_length=100, null=True)),
                ('invoice_no', models.CharField(blank=True, max_length=100, null=True)),
                ('bill_of_lading', models.CharField(blank=True, max_length=100, null=True)),
                ('billing_address', models.CharField(blank=True, max_length=100, null=True)),
                ('billing_contact', models.CharField(blank=True, max_length=100, null=True)),
                ('billing_gstin', models.CharField(blank=True, max_length=100, null=True)),
                ('billing_pan', models.CharField(blank=True, max_length=100, null=True)),
                ('billing_state', models.CharField(blank=True, max_length=100, null=True)),
                ('brokername', models.CharField(blank=True, max_length=100, null=True)),
                ('buyers_order_no', models.CharField(blank=True, max_length=100, null=True)),
                ('dated', models.CharField(blank=True, max_length=100, null=True)),
                ('dated2', models.CharField(blank=True, max_length=100, null=True)),
                ('delivery_date', models.CharField(blank=True, max_length=100, null=True)),
                ('destination', models.CharField(blank=True, max_length=100, null=True)),
                ('dispatch_doc_no', models.CharField(blank=True, max_length=100, null=True)),
                ('dispatch_through', models.CharField(blank=True, max_length=100, null=True)),
                ('motor_v_no', models.CharField(blank=True, max_length=100, null=True)),
                ('other_ref', models.CharField(blank=True, max_length=100, null=True)),
                ('shipping_address', models.CharField(blank=True, max_length=100, null=True)),
                ('shipping_contact', models.CharField(blank=True, max_length=100, null=True)),
                ('shipping_gstin', models.CharField(blank=True, max_length=100, null=True)),
                ('shipping_pan', models.CharField(blank=True, max_length=100, null=True)),
                ('shipping_state', models.CharField(blank=True, max_length=100, null=True)),
                ('shipping_company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('billing_company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('inr_no', models.CharField(blank=True, max_length=100, null=True)),
                ('ack_no', models.CharField(blank=True, max_length=100, null=True)),
                ('ack_date', models.CharField(blank=True, max_length=100, null=True)),
                ('delivery_note', models.CharField(blank=True, max_length=100, null=True)),
                ('terms_of_payment', models.CharField(blank=True, max_length=100, null=True)),
                ('terms_of_delivery', models.CharField(blank=True, max_length=200, null=True)),
                ('shipping_email', models.CharField(blank=True, max_length=200, null=True)),
                ('billing_email', models.CharField(blank=True, max_length=200, null=True)),
                ('e_way_no', models.CharField(blank=True, max_length=200, null=True)),
                ('freight', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProformUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc_id', models.IntegerField(null=True)),
                ('Desc', models.CharField(max_length=100, null=True)),
                ('product_id', models.IntegerField(null=True)),
                ('quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True)),
                ('sac', models.IntegerField(null=True)),
                ('rate', models.IntegerField(null=True)),
                ('unit', models.CharField(max_length=100, null=True)),
                ('cgst', models.IntegerField(blank=True, null=True)),
                ('igst', models.IntegerField(blank=True, null=True)),
                ('sgst', models.IntegerField(blank=True, null=True)),
                ('gst_type', models.CharField(max_length=100, null=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='api.proforminvoice')),
            ],
        ),
    ]
