# Generated by Django 4.1.3 on 2023-05-14 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='dated',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='delivery_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
