# Generated by Django 4.1.3 on 2023-07-11 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_quotation_quotation_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='user_client_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
