# Generated by Django 4.1.3 on 2023-07-11 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_quotation_user_client_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='item_id',
        ),
        migrations.AddField(
            model_name='item',
            name='item_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
