# Generated by Django 4.1.3 on 2023-07-11 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_item_costing_item_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='unit',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
