# Generated by Django 4.1.3 on 2023-05-19 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_user_gst_user_cgst_user_igst_user_sgst'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventorys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sac', models.IntegerField(null=True)),
                ('rate', models.IntegerField(null=True)),
                ('unit', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
