# Generated by Django 4.1.3 on 2023-07-11 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_item_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_id',
            field=models.IntegerField(blank=True, max_length=100, null=True),
        ),
    ]
