# Generated by Django 4.1.3 on 2023-05-19 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_inventorys'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorys',
            name='product_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
