# Generated by Django 4.1.3 on 2023-07-12 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_client_user_client_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotation',
            name='terms',
        ),
        migrations.AlterField(
            model_name='client',
            name='user_client_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='items',
            name='unit',
            field=models.CharField(blank=True, choices=[('METER', 'METER'), ('CENTI METER', 'CENTI METER'), ('MILI METER', 'MILI METER'), ('INCH', 'INCH'), ('FOOT', 'FOOT')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='user_client_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Terms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_terms', models.CharField(max_length=100, null=True)),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='api.quotation')),
            ],
        ),
    ]
