# Generated by Django 4.1.3 on 2023-05-19 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_inventorys_product_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='sac',
            new_name='product_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='rate',
        ),
    ]
