# Generated by Django 4.1.3 on 2023-07-14 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_quotation_terms_alter_client_user_client_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='size',
        ),
        migrations.AddField(
            model_name='items',
            name='depth',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='items',
            name='height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='items',
            name='length',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='items',
            name='width',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Terms',
        ),
    ]
