# Generated by Django 4.1.3 on 2023-05-19 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_user_rate_user_sac'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='delivery_note',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='terms_of_payment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
