# Generated by Django 4.1.3 on 2023-07-14 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_items_size_items_depth_items_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='discount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='special_note',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
