# Generated by Django 4.1.3 on 2023-05-19 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_invoice_delivery_note_invoice_terms_of_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='terms_of_delivery',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
