# Generated by Django 4.1.3 on 2023-07-14 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_quotation_discount_quotation_special_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='unit',
            field=models.CharField(blank=True, choices=[('SQR METER', 'SQR METER'), ('SQR CENTI METER', 'SQR CENTI METER'), ('SQR MILI METER', 'SQR MILI METER'), ('SQR INCH', 'SQR INCH'), ('SQR FOOT', 'SQR FOOT')], max_length=100, null=True),
        ),
    ]
