# Generated by Django 4.1.3 on 2023-07-15 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_items_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotation',
            name='total',
        ),
        migrations.AddField(
            model_name='quotation',
            name='total_with_discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
