# Generated by Django 4.1.3 on 2023-05-20 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_inventorys_total_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='billing_email',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='shipping_email',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
