# Generated by Django 4.1.3 on 2023-07-18 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_remove_quotation_total_quotation_total_with_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='numbers',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='running_foot',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='items',
            name='numbers',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='items',
            name='running_foot',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='items',
            name='unit',
            field=models.CharField(blank=True, choices=[('SQR METER', 'SQR METER'), ('MILI METER', 'MILI METER'), ('INCH', 'INCH'), ('SQR FOOT', 'SQR FOOT'), ('RUNNING FOOT', 'RUNNING FOOT'), ('NUMBERS', 'NUMBERS')], max_length=100, null=True),
        ),
    ]
