# Generated by Django 4.1.3 on 2023-05-30 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_invoice_billing_email_invoice_shipping_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='dated2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='e_way_no',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='freight',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
