# Generated by Django 4.1.3 on 2023-05-30 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_invoice_dated2_invoice_e_way_no_invoice_freight'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='File',
        ),
    ]
