# Generated by Django 4.1.3 on 2023-08-11 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='InteriorGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageName', models.CharField(max_length=100, null=True)),
                ('tag', models.CharField(choices=[('COMMERCIAL', 'COMMERCIAL'), ('HOME INTERIOR', 'HOME INTERIOR'), ('RETAIL SHOP', 'RETAIL SHOP'), ('DESIGN GALLERY', 'DESIGN GALLERY'), ('INTERIOR GALLERY', 'INTERIOR GALLERY')], max_length=100, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
