# Generated by Django 4.1.3 on 2023-08-11 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_interiorgallery_delete_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageName', models.CharField(max_length=100, null=True)),
                ('tag', models.CharField(choices=[('2D', '2D'), ('3D', '3D')], max_length=100, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='interiorgallery',
            name='tag',
            field=models.CharField(choices=[('COMMERCIAL', 'COMMERCIAL'), ('HOME INTERIOR', 'HOME INTERIOR'), ('RETAIL SHOP', 'RETAIL SHOP')], max_length=100, null=True),
        ),
    ]
