# Generated by Django 4.1.3 on 2023-05-30 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_invoice_client_id_alter_invoice_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='File',
            new_name='User',
        ),
    ]
