# Generated by Django 4.1.3 on 2023-08-11 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_designgallery_image_interiorgallery_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designgallery',
            name='image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='interiorgallery',
            name='image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
