# Generated by Django 4.1.3 on 2023-12-15 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_status_items_quantity_quotation_remark_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='status',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
