# Generated by Django 4.1.3 on 2023-12-27 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_alter_quotation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='date',
            field=models.CharField(blank=True, default='27/12/23', max_length=100, null=True),
        ),
    ]
