# Generated by Django 4.1.3 on 2024-01-01 10:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_designer', models.BooleanField(default=False)),
                ('is_secendory_process', models.BooleanField(default=False)),
                ('is_embroidary', models.BooleanField(default=False)),
                ('is_cutting', models.BooleanField(default=False)),
                ('is_production', models.BooleanField(default=False)),
                ('is_accountent', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
