# Generated by Django 4.1.3 on 2024-01-01 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='is_accountent',
            new_name='is_customer',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='is_cutting',
            new_name='is_staff',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='is_designer',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='is_embroidary',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='is_production',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='is_secendory_process',
        ),
    ]
