# Generated by Django 4.1.3 on 2023-05-10 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='roo',
        ),
        migrations.AddField(
            model_name='student',
            name='roll',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
