# Generated by Django 4.1.3 on 2023-06-02 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_useraccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='create',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='view',
            field=models.BooleanField(default=False),
        ),
    ]
