# Generated by Django 4.1.3 on 2024-01-12 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_useraccount_is_super_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='is_customer',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='is_staff',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='is_superuser',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
