# Generated by Django 4.2.10 on 2024-06-06 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_useraccount_career_alter_useraccount_education_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('moon_board', models.FileField(blank=True, null=True, upload_to='mood_boards/')),
            ],
        ),
    ]
