# Generated by Django 4.1.3 on 2023-06-02 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_useraccount_is_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='name',
        ),
        migrations.AddField(
            model_name='useraccount',
            name='USERNAME_FIELD',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='first_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='last_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='is_staff',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
