# Generated by Django 4.1.3 on 2023-06-05 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_useraccount_is_admin_remove_useraccount_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='USERNAME_FIELD',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='last_name',
        ),
        migrations.AddField(
            model_name='useraccount',
            name='is_admin',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='is_staff',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
