# Generated by Django 4.1.3 on 2023-06-05 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_useraccount_is_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='is_admin',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
