# Generated by Django 4.1.3 on 2023-06-06 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_useraccount_groups_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choices',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='UserAccount',
        ),
    ]
